### PR TITLE
fix: directory import error when using esm

### PR DESCRIPTION
**Pull request by codebutler**
Fixes this error:
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Directory import '/code/node_modules/.pnpm/@suspensive+react@1.14.8_react@18.2.0/node_modules/use-sync-external-store/shim' is not supported resolving ES modules imported from /code/node_modules/.pnpm/@suspensive+react@1.14.8_react@18.2.0/node_modules/@suspensive/react/dist/index.js
Did you mean to import use-sync-external-store@1.2.0_react@18.2.0/node_modules/use-sync-external-store/shim/index.js?
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:319:17)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///code/node_modules/.pnpm/@suspensive+react@1.14.8_react@18.2.0/node_modules/use-sync-external-store/shim'
}

Node.js v18.15.0
```

# Overview

## PR Checklist

- [ ] I have written documents and tests, if needed.

### CODE REVIEW

**Comment by codebutler** [comment]
by the way this "experimental" file is imported even when not explicitly used:

https://github.com/suspensive/react/blob/728607a4cf3885feed1e45dbc88a680fe06de863/packages/react/src/ErrorBoundary.tsx#L19

**Comment by manudeli** [comment]
@codebutler How can I reproduce error? I tried reproducing this error but I couldn't🥲https://stackblitz.com/edit/vitejs-vite-zwyyo9?file=src%2FApp.jsx

Could you leave me link to reproduce this error? GitHub, Stackblitz or any other platform okay

**Comment by manudeli** [comment]
> by the way this "experimental" file is imported even when not explicitly used:
> 
> https://github.com/suspensive/react/blob/728607a4cf3885feed1e45dbc88a680fe06de863/packages/react/src/ErrorBoundary.tsx#L19

Initially I was hoping to have awaitClient.reset handled by ErrorBoundary.reset in one go. However, it appears that this role would be better suited to ErrorBoundary.onReset externally. In your opinion, it seems like a good idea to remove awaitClient.reset from ErrorBoundary. Could you please make a Pull Request?

**Comment by codebutler** [comment]
opened #205. can this be merged too?

**Comment by manudeli** [comment]
> opened #205. can this be merged too?

@codebutler I merged it. Thanks

**Comment by manudeli** [comment]
@codebutler Thank you for suggestion as a Pull Request. I'm curious about the problem you're having. I would appreciate it if you could reproduce the problem so I could see it, like [the stackblitz link I gave you](https://github.com/suspensive/react/pull/203#issuecomment-1745788607).

**Comment by codebutler** [comment]
> @codebutler Thank you for suggestion as a Pull Request. I'm curious about the problem you're having. I would appreciate it if you could reproduce the problem so I could see it, like [the stackblitz link I gave you](https://github.com/suspensive/react/pull/203#issuecomment-1745788607).

Sorry I haven't had time to create a reproducible example. I originally ran into this problem when using [vite-node](https://www.npmjs.com/package/vite-node) so it might have something to do with whatever flags it runs node with.

**Comment by manudeli** [comment]
@codebutler I'm sorry it took so long to resolve this issue. we removed `<Await/>` from @suspensive/react from v1.17.2 So we don't use use-sync-external-store and I'm hoping that will solve your problem as well. If the problem persists, please mention me at any time. Thank you for reporting the issue.

cc. @okinawaa @minsoo-web

**Pull request closed without merging**
