### PR TITLE
chore(react-query): fix LICENSE.md in @suspensive/react-query to conform MIT license of toss/slash

### LINKED ISSUE #37: [Feature]: Resolve LICENSE problem
Resolve https://github.com/TanStack/query/pull/5303

- [x] Add to an existing package

Package name: @suspensive/react-query

### PR DESCRIPTION
**Pull request by manudeli**
fix #37 

# Fix LICENSE.md in @suspensive/react-query
With this PR(https://github.com/TanStack/query/pull/5259), Documentation of @suspensive/react-query was added to the Community Resources section of TanStack/query's official documentation, and then reverted by @BasixKOR's this PR(https://github.com/TanStack/query/pull/5303)

The reason we discussed was that @suspensive/react-query started from the code of @toss/react-query, but we didn't mark it in LICENSE.md.

### so What I followed (@raon0211's guide)
https://gist.github.com/fbaierl/1d740a7925a6e0e608824eb27a429370

### CODE REVIEW

**Comment by manudeli** [comment]
@raon0211 @BasixKOR, I followed MIT License you guided. Could you check this Pull Request out please?

**Comment by ChanhyukPark-Tech** [comment]
There was this part.
I checked! I think it'll be okay if we get two people's confirmation you mentioned

**Review by raon0211 — APPROVED** [review]
Looks okay to me. Thanks for the heads-up!

**Review by raon0211 — APPROVED** [review]
Looks okay to me. Thanks for the heads-up!

**Review by ChanhyukPark-Tech — APPROVED** [review]

**Pull request merged**
