### PR TITLE
feat(react): update useErrorBoundary from experimental to stable

### LINKED ISSUE #200: [Feature]: Remove experimental mark of useErrorBoundary
### **Package Scope**

- [x] Add to an existing package

Package name: @suspensive/react

### **Overview**

Remove unnecessary field of useErrorBoundary

### PR DESCRIPTION
**Pull request by manudeli**
fix #200 

# Overview

I updated @suspensive/react's useErrorBoundary to stable from experimental

## PR Checklist

- [x] I did below actions if need

1. I read the [Contributing Guide](https://github.com/suspensive/react/blob/main/CONTRIBUTING.md)
2. I added documents and tests.

### CODE REVIEW

**Review by minsoo-web — APPROVED** [review]
Cool ! 👍

**Comment by manudeli** [comment]
@okinawaa check this Pull Request please. this is important change so I mentioned you to get review before release

**Review by okinawaa — APPROVED** [review]
thank you for good work 👍

**Comment by manudeli** [comment]
We made all apis related with ErrorBoundary as stable from now🚀

**Pull request merged**
