### PR TITLE
fix(react): remove useless variable assigning in useIsomorphicLayoutEffect

### LINKED ISSUE #281: [Feature]: isClient
### Package Scope

@suspensive/react

### Description

I noticed that `isClient` is used inside `useIsomorphicLayoutEffect`. 

Couldn't "isClient" be managed in `@suspicious/react/utils`? Additionally, I think `isSever` could be defined and utilized as well.

However, currently the only code that uses "isClient" is "useIsomorphicLayoutEffect". Whether this should be managed in "utils" depends on the maintainer's thoughts.

If you agree with the above, I can work on that and adding test code.

Please let me know what you think! 🙏

### Possible Solution

```ts
export const isClient = typeof window !== 'undefined'
```

```ts
export const isServer = !isClient()
```

### etc.

_No response_

### PR DESCRIPTION
**Pull request by minsoo-web**
fix #281 

# Overview

I remove isClient in `useIsomorphicLayoutEffect`

## PR Checklist

- [x] I did below actions if need

1. I read the [Contributing Guide](https://github.com/suspensive/react/blob/main/CONTRIBUTING.md)
2. I added documents and tests.

### CODE REVIEW

**Review by manudeli — COMMENTED** [review]
@minsoo-web Could you recommit and push with adding @ssi02014 as co-author? He definitely contribute about this as report issue and make conversation.

**Comment by ssi02014** [comment]
@manudeli Thank you! 🙏
@minsoo-web 
There is also the same code in `test-utils/ThrowError`, which should be fixed 😄

**Comment by minsoo-web** [comment]
@manudeli Yes! I add co-author with @ssi02014 thanks!
@ssi02014 I remove it too! [fix(react): remove useless function define in ThrowError](https://github.com/suspensive/react/pull/283/commits/33de299ebc51c2cf70e3dd3fe8911a89cfffd159) thanks!

**Review by manudeli — APPROVED** [review]
@ssi02014 @minsoo-web Thanks!

**Comment by ssi02014** [comment]
Cool !

**Pull request merged**
